/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coolchat;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import javax.swing.JOptionPane;

/**
 *
 * @author darkheart
 */
public class ChatPanelClient extends javax.swing.JFrame {
    int     port = 0;
    String  ip_address = "127.0.0.1";
    
    static Socket s;
    static DataInputStream dis;
    static DataOutputStream dos;

    /**
     * Creates new form ChatPanelClient
     */
    public ChatPanelClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        txt_clientMsg = new javax.swing.JTextField();
        btn_sendMsg = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_ChatClient = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Client Chat");

        txt_clientMsg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_clientMsgKeyPressed(evt);
            }
        });

        btn_sendMsg.setText("...");
        btn_sendMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendMsgActionPerformed(evt);
            }
        });

        txt_ChatClient.setEditable(false);
        txt_ChatClient.setColumns(20);
        txt_ChatClient.setRows(5);
        jScrollPane1.setViewportView(txt_ChatClient);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_clientMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_sendMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_clientMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sendMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
    private void sendMsg(){
        String MsgOut = "";
        String ClientString = "Client:";
        MsgOut = txt_clientMsg.getText().trim();
        System.out.println(MsgOut);
        if(MsgOut.equals("/quit")){
            this.quitChat();
        }    
        MsgOut = ClientString + " " + MsgOut;
        try{
            txt_ChatClient.append(MsgOut+"\n");   

            if(dos!=null)
                dos.writeUTF(MsgOut);
                
            txt_clientMsg.setText("");

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void quitChat(){
        
        try {
            System.out.println("QUIT");
            dos.close();
            dis.close();
            s.close();
            this.dispose();
        } catch (IOException e) {
            //JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btn_sendMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendMsgActionPerformed
        this.sendMsg();

    }//GEN-LAST:event_btn_sendMsgActionPerformed

    
    private void txt_clientMsgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_clientMsgKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            this.sendMsg();
        }
    }//GEN-LAST:event_txt_clientMsgKeyPressed
    
    public void startClient()
    {
        if(this.port == 0)
            return;       
        
        Thread t = new Thread(new Runnable() {
            public void run() {
                try{
                    String MsgIn = "";

                    s   = new Socket(ip_address,port);
                    dis = new DataInputStream(s.getInputStream());
                    dos = new DataOutputStream(s.getOutputStream());
                    
                    while(!MsgIn.equals("/quit")){
                        MsgIn = dis.readUTF();
                        System.out.print(MsgIn);
                        txt_ChatClient.setText(txt_ChatClient.getText().trim()  +"\n"+ MsgIn +"\n");
                    }
                                        
                    
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
                }
                
            }
        });
        t.start();

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatPanelClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatPanelClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatPanelClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatPanelClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatPanelClient().setVisible(true);
            }
        });
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sendMsg;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.TextArea textArea1;
    private javax.swing.JTextArea txt_ChatClient;
    private javax.swing.JTextField txt_clientMsg;
    // End of variables declaration//GEN-END:variables
}
