/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coolchat;

import javax.swing.JOptionPane;

/**
 *
 * @author darkheart
 */
public class ControlPanel extends javax.swing.JFrame {

    /**
     * Creates new form ControlPanel
     */
    public ControlPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rb_client = new javax.swing.JRadioButton();
        rb_server = new javax.swing.JRadioButton();
        txt_ipaddress = new java.awt.TextField();
        txt_port = new java.awt.TextField();
        lbl_ipaddress = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_start = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cool Chat Settings");

        rb_client.setText("Client");
        rb_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_clientActionPerformed(evt);
            }
        });

        rb_server.setText("Server");
        rb_server.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_serverActionPerformed(evt);
            }
        });

        txt_ipaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ipaddressActionPerformed(evt);
            }
        });

        lbl_ipaddress.setText("IP Address :");

        jLabel2.setText("Port :");

        btn_start.setText("Start");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_start)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rb_client)
                            .addGap(44, 44, 44)
                            .addComponent(rb_server))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_ipaddress)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_ipaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(txt_port, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_client)
                            .addComponent(rb_server))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lbl_ipaddress))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(txt_ipaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addComponent(txt_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btn_start)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_clientActionPerformed
        
        rb_server.setSelected(false);
        lbl_ipaddress.setVisible(true);
        txt_ipaddress.setEditable(true);
        txt_ipaddress.setVisible(true);
        
    }//GEN-LAST:event_rb_clientActionPerformed

    private void rb_serverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_serverActionPerformed

        rb_client.setSelected(false);
        lbl_ipaddress.setVisible(false);
        txt_ipaddress.setVisible(false);
        txt_ipaddress.setEnabled(false);
        
    }//GEN-LAST:event_rb_serverActionPerformed

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        // TODO add your handling code here:
        if (txt_port.getText() == null || txt_port.getText().trim().isEmpty()) {
             JOptionPane.showMessageDialog(null, "No port is selected", "Error", JOptionPane.ERROR_MESSAGE);
             return;
        }        
        int port = Integer.parseInt(txt_port.getText());
        if(rb_server.isSelected()){
            ChatPanelServer cps = new ChatPanelServer();
            cps.port = port;
            
            cps.setVisible(true);
            this.dispose();
            cps.startServer();
            
            

        }else if(rb_client.isSelected()){
            if (txt_ipaddress.getText() == null || txt_ipaddress.getText().trim().isEmpty()) {
                 JOptionPane.showMessageDialog(null, "No Server IP is selected", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }   
            String ip_address = txt_ipaddress.getText();
            ChatPanelClient cpc = new ChatPanelClient();
            cpc.port = port;
            cpc.ip_address = ip_address;
            
            cpc.setVisible(true);
            this.dispose();
            cpc.startClient();
            
        }
    }//GEN-LAST:event_btn_startActionPerformed

    private void txt_ipaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ipaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ipaddressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_start;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_ipaddress;
    private javax.swing.JRadioButton rb_client;
    private javax.swing.JRadioButton rb_server;
    private java.awt.TextField txt_ipaddress;
    private java.awt.TextField txt_port;
    // End of variables declaration//GEN-END:variables
}
